users:
  admin:
    email: mTpLlTtqhUceRhxuerKcCg==.RSKZ/xDXYKio2oq+z652YHvNb0lNkA2qLw==
    role: owner
ranges:
  - name: Headers
    range: Sheet1!1:1
    warn: true
    editors:
      - admin
  - name: My Named Range
    range: Sheet1!A1:B2
    editors:
      - john_smith
